#!/bin/sh
if [ $# -lt 1 ]; then
    echo "Start R and load file given as argument."
    echo "Usage: $(basename $0) FILE"
    exit 1
fi
cd "$(dirname "$1")" || exit 1
# Requires code to read the data in ~/.Rprofile.
# https://stackoverflow.com/a/29683963/16369038
R --quiet --no-save --args "$(basename "$1")"
